### ISSUE TITLE
[DEBUG] Cannot read properties of undefined (reading 'get')

### ISSUE THREAD

**Issue by sanjose-j** [twilio-labs/serverless-toolkit#431]
Hi, i am experiencing an error when creating a serverless project.
I am following this tutorial on creating Audio Livestream App
https://www.twilio.com/blog/build-audio-livestream-app-twilio-live

Here's the debug error for reference

```
[DEBUG] Found command "serverless:init" plugin: @twilio-labs/plugin-serverless
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/serverless-toolkit/issues"
[DEBUG] Cannot read properties of undefined (reading 'get')
[DEBUG] TypeError: Cannot read properties of undefined (reading 'get')
    at getWindowSize (C:\Users\inggo\.twilio-cli\node_modules\create-twilio-function\src\create-twilio-function\window-size.js:8:34)
    at successMessage (C:\Users\inggo\.twilio-cli\node_modules\create-twilio-function\src\create-twilio-function\success-message.js:24:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createTwilioFunction (C:\Users\inggo\.twilio-cli\node_modules\create-twilio-function\src\create-twilio-function.js:183:11)
    at async FunctionsInit._run (C:\Users\inggo\.twilio-cli\node_modules\@oclif\core\lib\command.js:79:22)
    at async Config.runCommand (C:\Users\inggo\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\core\lib\config\config.js:272:25)
    at async Object.run (C:\Users\inggo\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\core\lib\main.js:76:5)
 »   Error: EEXIT: 1
 »   Code: EEXIT
```

**Comment by dkundel** [comment]
Hi @sanjose-! Could you let me know which version of Node.js you are using?

**Comment by sanjose-j** [comment]
@dkundel Hello! I'm using v16.17.1

**Comment by thedeec1** [comment]
Did this ever get resolved I've ecounted the same error, using node v16.17.0

[DEBUG] Cannot read properties of undefined (reading 'get')
[DEBUG] TypeError: Cannot read properties of undefined (reading 'get')
    at getWindowSize (C:\Users\d_cotton\.twilio-cli\node_modules\create-twilio-function\src\create-twilio-function\window-size.js:8:34)
    at successMessage (C:\Users\d_cotton\.twilio-cli\node_modules\create-twilio-function\src\create-twilio-function\success-message.js:24:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createTwilioFunction (C:\Users\d_cotton\.twilio-cli\node_modules\create-twilio-function\src\create-twilio-function.js:183:11)
    at async FunctionsInit._run (C:\Users\d_cotton\.twilio-cli\node_modules\@twilio\cli-core\node_modules\@oclif\core\lib\command.js:80:22)
    at async Config.runCommand (C:\Users\d_cotton\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\core\lib\config\config.js:272:25)
    at async Object.run (C:\Users\d_cotton\AppData\Roaming\npm\node_modules\twilio-cli\node_modules\@oclif\core\lib\main.js:74:5)
 »   Error: EEXIT: 1
 »   Code: EEXIT

**Comment by makserik** [comment]
Hi @sanjose-j @thedeec1 are you still having this issue? Please note the minimum required node version now is 18.
